name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Release-Notes-Preview
      # You may pin to the exact commit or the version.
      # uses: snyk/release-notes-preview@77b57680e453abd052d6e029e84037b644251ee8
      uses: snyk/release-notes-preview@v1.6.1
      continue-on-error: true
      with:
        # Branch where the Semantic Release will occur.
        releaseBranch: master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_GH_TOKEN }}
    - name: driftctl-action
      # You may pin to the exact commit or the version.
      # uses: snyk/driftctl-action@bc3f70f444b1bda780ebe6fc277bac0a639f4d49
      uses: snyk/driftctl-action@v1.1.1
      continue-on-error: true
      with:
        # The version of driftctl to install.
        version: latest
    - name: Snyk
      # You may pin to the exact commit or the version.
      # uses: snyk/actions@7fad562681122205233d1242c3bb39598c5393da
      uses: snyk/actions@0.3.0
      continue-on-error: true # To make sure that SARIF upload gets called
      with:
        # Which Snyk command to run, defaults to test
        command: test
        # Additional arguments to pass to Snyk
        #args: # optional
        # Output a snyk.json file with results if running the test command
        #json: # optional
        args: --sarif-file-output=snyk.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif

